INFO 2022-09-12 07:25:42,343 - Start time: 20220912T072542
WARNING 2022-09-12 07:25:56,461 - Exception encountered in fetch_trial_data. Traceback: Traceback (most recent call last):
  File "/global/cscratch1/sd/yazbeck/boa/boa/metaclasses.py", line 19, in wrapper
    return func(*args, **kwargs)
  File "/global/cscratch1/sd/yazbeck/boa/boa/wrapper_utils.py", line 52, in wrapper
    return func(*args, **kwargs)
  File "/global/cscratch1/sd/yazbeck/US_LA3_Wetl_C3Gra_Trans/elm_wrapper.py", line 432, in fetch_trial_data
    y_pred, y_true = get_model_obs(
  File "/global/cscratch1/sd/yazbeck/US_LA3_Wetl_C3Gra_Trans/elm_wrapper.py", line 275, in get_model_obs
    modeldf["CH4_SURF_AERE_TOT"] = np.multiply(AllModelVar[:,0],AllModelVar[:,2])+np.multiply(AllModelVar[:,1],(1-AllModelVar[:,2]))
  File "/global/homes/y/yazbeck/.conda/envs/boa_env_cori/lib/python3.9/site-packages/pandas/core/frame.py", line 3655, in __setitem__
    self._set_item(key, value)
  File "/global/homes/y/yazbeck/.conda/envs/boa_env_cori/lib/python3.9/site-packages/pandas/core/frame.py", line 3832, in _set_item
    value = self._sanitize_column(value)
  File "/global/homes/y/yazbeck/.conda/envs/boa_env_cori/lib/python3.9/site-packages/pandas/core/frame.py", line 4535, in _sanitize_column
    com.require_length_match(value, self.index)
  File "/global/homes/y/yazbeck/.conda/envs/boa_env_cori/lib/python3.9/site-packages/pandas/core/common.py", line 557, in require_length_match
    raise ValueError(
ValueError: Length of values (8015) does not match length of index (8016)

